---
# - name: Configure node ip
#   vars:
#     node_ip: "{{ ansible_default_ipv4.address }}"
#   lineinfile:
#     path: /etc/default/kubelet
#     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

# - name: Restart kubelet
#   service:
#     name: kubelet
#     daemon_reload: yes
#     state: restarted

- name: Initialize Cluster
  # vars:
  #   node_ip: "{{ ansible_default_ipv4.address }}"
  #   hostname: "{{ ansible_fqdn }}"
  command: kubeadm init --apiserver-advertise-address=192.168.164.30 --apiserver-cert-extra-sans=192.168.164.30 --node-name k8head --pod-network-cidr=10.15.0.0/16
  
- name: Create kubeconfig Directory
  file:
    path: /home/{{ k8User }}/.kube
    state: directory
    owner: "{{ k8User }}"
    group: "{{ k8User }}"
  
- name: Copy kube Config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ k8User }}/.kube/config
    remote_src: true
    owner: "{{ k8User }}"
    group: "{{ k8User }}"

- name: Install Pod Network add-on Calico
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  
- name: Generate kube join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./files/join_command"

...
